version: "3.1"
services:
  web:
    image: dummy-rails
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DUMMY_DATABASE_PASSWORD: dummy_secret_passwd
      DATABASE_URL: "postgres://dummy:dummy-ruby123@db/development"
      REDIS_URL: "redis:6379"
    command: ash -c "sleep 10 && rails db:migrate && bin/rails server"

  sidekiq:
    image: dummy-rails
    command: bundle exec sidekiq
    depends_on:
      - web

  crono:
    image: dummy-rails
    command: ash -c "sleep 15 && bundle exec crono"
    environment:
      DUMMY_DATABASE_PASSWORD: dummy_secret_passwd
      DATABASE_URL: "postgres://dummy:dummy-ruby123@db/development"
    depends_on:
      - web

  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: dummy
      POSTGRES_PASSWORD: dummy-ruby123
      POSTGRES_DB: development

  redis:
    image: redis:alpine
